name: System Test

on:
  push:
    branches: [ master ]
    paths:
    - 'Team36/**'
  pull_request:
  workflow_dispatch:

env:
  FILE_PATH: '.\Team36\Code36\'

jobs:
  build-and-test:
      runs-on: windows-latest
      steps:
        - uses: actions/checkout@v2
        - name: Setup MSBuild and add to PATH
          uses: microsoft/setup-msbuild@v1.1
          id: setup_msbuild

        - name: Run MSBuild
          id: run_msbuild
          working-directory: ${{ env.FILE_PATH }}
          run: msbuild .\StartupSPASolution.sln

        - name: Setup Python
          uses: actions/setup-python@v2
          with:
            python-version: 3.8
        - name: Run System Test Script
          run: |
            python run_tests.py ci
