name: Unit and Integration Tests

on:
  push:
    branches: [ master ]
    paths:
    - 'Team36/Code36/**'
  pull_request:
  workflow_dispatch: 

env:
  FILE_PATH: '.\Team36\Code36\'
  TEST_FILE_PATH: '.\Team36\Code36\Debug\'

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup MSBuild and add to PATH
      uses: microsoft/setup-msbuild@v1.1
      id: setup_msbuild

    - name: Run MSBuild
      id: run_msbuild
      working-directory: ${{ env.FILE_PATH }}
      run: msbuild .\StartupSPASolution.sln

    - name: Setup VSTest and add to PATH
      id: setup_vstest
      uses: darenm/Setup-VSTest@v1

    - name: Run Unit Test
      id: run_UT
      working-directory: ${{ env.TEST_FILE_PATH }}
      run: vstest.console.exe /Platform:x86 .\UnitTesting.dll

    - name: Run Integration Test
      id: run_IT
      working-directory: ${{ env.TEST_FILE_PATH }}
      run: vstest.console.exe /Platform:x86 .\IntegrationTesting.dll
